services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    read_only: false
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8082:8082"
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PROVIDER_OVERRIDE_STEPFUNCTIONS=v2
      - USE_LIGHT_IMAGE=0
      - DEBUG=1
      - PORT_WEB_UI=8082
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - START_WEB=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"  # required for some AWS services like AWS Lambda
    security_opt:
      - no-new-privileges:true

  datadog:
    image: "gcr.io/datadoghq/agent:7"
    env_file:
      - local.env
    environment:
      - DD_API_KEY=${DATADOG_APP_KEY}
      - DD_HOSTNAME=datadog-agent
      - DD_SITE=us5.datadoghq.com
      - DD_LOG_LEVEL=error
    ports:
      - "8126:8126"